[IMPL] Pointer type autogeneration added
Perksey/SilkX pull request #5
Opened 2023-10-18 20:03 UTC by curin

## Table of Contents

* [Code of Conduct](#code-of-conduct)
* [Proposal Implementation](#proposal-implementation)

### Code of Conduct

This project has adopted the code of conduct defined by the [Contributor Covenant](http://contributor-covenant.org/) 
to clarify expected behavior in our community. For more information, see the [.NET Foundation Code of Conduct](http://www.dotnetfoundation.org/code-of-conduct).

## Proposal Implementation

[IMPL] Pointer type auto-generation added
- Pointer types up to a depth of 3 have been generated and added to the project
- Extension methods have been added into Core to support converting to strings from valid types
- Previous pointer tests have been retrofitted for the new types

2023-10-18 21:28 UTC, Perksey requested changes

2023-10-18 21:28 UTC, Perksey commented on eng/pointergen/Generator.cs
> +            File.WriteAllText(Path.Combine(outputDir, name + ".generic.gen.cs"), text);
How come IL weaving is used for the single-dimension generic ones?

2023-10-18 21:28 UTC, Perksey commented on eng/pointergen/Generator.cs
> +    public unsafe static implicit operator byte*({{name}} ptr) => (byte*)Unsafe.AsPointer({{getObjectRef}});
```suggestion
    public unsafe static explicit operator byte*({{name}} ptr) => (byte*)Unsafe.AsPointer({{getObjectRef}});
```
Unsafe.AsPointer is unsafe and should be an explicit op.

2023-10-18 21:28 UTC, Perksey commented on eng/pointergen/Generator.cs
> +    public unsafe static implicit operator void*({{name}} ptr) => Unsafe.AsPointer({{getObjectRef}});
```suggestion
    public unsafe static explicit operator void*({{name}} ptr) => Unsafe.AsPointer({{getObjectRef}});
```
Unsafe.AsPointer is unsafe and should be an explicit op.

2023-10-18 21:28 UTC, Perksey commented on eng/pointergen/Generator.cs
> +    public static implicit operator {{name}}(byte[,] array) => MemoryMarshal.CreateSpan(ref array[0, 0], array.Length);
Does array.Length get the sum of all dimensions (i.e. the length of the array when flat)?

2023-10-18 21:28 UTC, Perksey commented on eng/pointergen/Generator.cs
> +    public static implicit operator void*({{fullName}} ptr) => Unsafe.AsPointer(ref Unsafe.AsRef(in ptr.InteriorRef));
```suggestion
    public static explicit operator void*({{fullName}} ptr) => Unsafe.AsPointer(ref Unsafe.AsRef(in ptr.InteriorRef));
```

2023-10-18 21:28 UTC, Perksey commented on eng/pointergen/Generator.cs
> +    public {{name}}(ref {{rOField}}byte @InteriorRef)
Do we want this to be public?

2023-10-18 21:28 UTC, Perksey commented on eng/pointergen/Generator.cs
> +            IL.Emit.Sizeof<nuint>();
```suggestion
            IL.Emit.Sizeof<{types.Length > 1 ? "nuint" : arrayType}>();
```

2023-10-18 21:28 UTC, Perksey commented on eng/pointergen/Generator.cs
> +            IL.Emit.Sizeof<nuint>();
```suggestion
            IL.Emit.Sizeof<{types.Length > 1 ? "nuint" : arrayType}>();
```

2023-10-18 21:28 UTC, Perksey commented on sources/Core/Pointers/MutMut.gen.cs
> +    /// Creates a <see cref="MutMut"/> from a string span.
```suggestion
    }

    /// <summary>
    /// Creates a <see cref="MutMut"/> from a string span.
```

2023-10-18 21:28 UTC, Perksey commented on sources/Core/Pointers/MutMutPtr.gen.cs
> +    public readonly ref MutMut Ref
This is frazzling me a little bit. iirc in Discord we decided `MutMutPtr` is read as "a mutable pointer to a mutable pointer to an immutable pointer [to a T]" so should this be `ref MutPtr`?

iirc we also wanted to make this a constant we can tweak just in case we back-track

2023-10-18 21:28 UTC, Perksey commented on sources/Core/Pointers/MutMut.generic.gen.cs
> +    public static implicit operator MutMut<T>(string[] array)
We should not expose these operators if the innermost dimension is mutable, as strings in C# are not meant to be mutable.

2023-10-18 21:28 UTC, Perksey commented on sources/Core/Pointers/MutPtr.gen.cs
> +    private readonly ref byte InteriorRef;
I think this might need to be a `readonly ref readonly`, could be wrong though.

2023-10-18 21:28 UTC, Perksey commented on sources/SilkTouchX/Program.cs
> +System.Threading.Thread.Sleep(1000);
?

2023-10-18 21:28 UTC, Perksey commented on tests/Silk.NET.Core.UnitTests/MutMutTests.cs
> +public class MutMutTests
Can you pull in the latest main (hopefully fixing CI)

2023-10-18 21:28 UTC, Perksey commented on sources/GLFW/glfw3/Glfw.gen.cs
> +    public static Mut<Cursor> CreateCursor([NativeTypeName("const GLFWimage *")] Ptr<Image> image, int xhot, int yhot)
NICE!

2023-10-18 21:31 UTC, Perksey commented on eng/pointergen/Generator.cs
> +        => SilkMarshal.JaggedArrayToPointerArray<{{arrayType}}>(array);
We also need to discuss whether we want to expose these operators for mutable array types. If the pointer is mutated by native, the original pointer won't be modified, rather it'll be the pointer array that's allocated by JaggedArrayToPointerArray/StringArrayToArray. It'd be an unfortunate deficiency to only be able to pass arrays of arrays if all but the inner dimension is immutable, but one that may be necessary.

2023-10-18 21:41 UTC, Khitiara commented on eng/pointergen/Generator.cs
> +    public static implicit operator {{name}}(byte[,] array) => MemoryMarshal.CreateSpan(ref array[0, 0], array.Length);
![image](https://github.com/Perksey/SilkX/assets/3117019/aa41f02d-6afe-45f7-8618-e901a9e66364)
per the docs on the Array type yes

2023-10-18 21:42 UTC, Perksey commented on eng/pointergen/Generator.cs
> +    public static implicit operator {{name}}(byte[,] array) => MemoryMarshal.CreateSpan(ref array[0, 0], array.Length);
Thanks :)

2023-10-18 22:16 UTC, curin commented on sources/SilkTouchX/Program.cs
> +System.Threading.Thread.Sleep(1000);
Oh I thought I removed that, it was to get the compiler to stop while I was debugging

2023-10-18 22:17 UTC, curin commented on sources/Core/Pointers/MutMutPtr.gen.cs
> +    public readonly ref MutMut Ref
I think I got this reversed in my head at some point, I should be able to fix it pretty easy.

2023-10-18 23:20 UTC, curin commented on eng/pointergen/Generator.cs
> +            File.WriteAllText(Path.Combine(outputDir, name + ".generic.gen.cs"), text);
There is a bit of crossover with all the generics, it was easier to have it IL weave rather than separate it out. The more shared sections the easier it will be to maintain. I could have it not IL weave if you would prefer.

2023-10-18 23:54 UTC, Perksey commented on eng/pointergen/Generator.cs
> +            File.WriteAllText(Path.Combine(outputDir, name + ".generic.gen.cs"), text);
I think it's best to address all the extant comments first and then once that's done, we can see if there's an easy way to make the single-dimension method handle generics as well.

2023-10-19 00:39 UTC, Perksey commented on eng/pointergen/Generator.cs
> +        const bool OUTERMOST_ON_RIGHT = true;
Are we getting our wires crossed on the definition here? I would imply given the current rules that this would be `false` i.e. "pointer1 to pointer2 to byte" the "innermost" (i.e. the most amount of dereferences you need to do to get to that point) is the byte, followed by `pointer2` ergo the innermost is on the right surely?

2023-10-19 01:08 UTC, curin commented on eng/pointergen/Generator.cs
> +        const bool OUTERMOST_ON_RIGHT = true;
okay this is to control the order of how MutMutPtr so Ptr is the outermost and Mut is innermost (outermost is on the right, <<Mut>Mut>Ptr). Is that not what we want?

2023-10-19 01:13 UTC, Perksey commented on eng/pointergen/Generator.cs
> +        const bool OUTERMOST_ON_RIGHT = true;
I think that's what I originally wanted, but then following [this discussion](https://discord.com/channels/521092042781229087/587346162802229298/1163617967058202624) it was changed to:
```cs
ref int Dereference(MutPtrMut<int> outermost)
{
    ref PtrMut<int> secondOutermost = ref outermost[0];
    ref readonly Mut<int> secondInnermost = ref secondOutermost[0];
    return ref secondInnermost[0];
}
```

2023-10-19 01:13 UTC, Perksey commented on eng/pointergen/Generator.cs
> +        const bool OUTERMOST_ON_RIGHT = true;
(the change has not been reflected in the proposal tmk)

2023-10-19 01:41 UTC, curin commented on eng/pointergen/Generator.cs
> +        const bool OUTERMOST_ON_RIGHT = true;
fixed

2023-10-19 01:57 UTC, curin commented on eng/pointergen/Generator.cs
> +    public {{name}}(ref {{rOField}}byte @InteriorRef)
no, but it does need to at least be internal (it is used by generics for their non-generic conversions)

2023-10-19 23:12 UTC, Perksey commented on sources/Core/Pointers/MutMutPtr.gen.cs
> +    public readonly ref MutMut Ref
I think there are multiple issues at play here.

The mutability and type names seem to be out of sync. For instance `MutMutPtr` was a `ref readonly MutPtr`, now it's a `ref MutMut`. I think it needs to be `ref MutPtr` (the `ref` is the stand-in for the Mut)

2023-10-20 02:42 UTC, Khitiara commented on sources/SilkTouchX/Program.cs
> +System.Threading.Thread.Sleep(1000);
[The Debugger class](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debugger?view=net-7.0) exists for future reference, the Launch method pauses and attaches a debugger all at once

2023-10-20 14:04 UTC, curin commented on sources/Core/Pointers/MutMutPtr.gen.cs
> +    public readonly ref MutMut Ref
This should be fixed now

2023-10-21 23:25 UTC, Perksey approved these changes

2023-10-21 23:25 UTC, merged